apiVersion: v1
kind: Secret
metadata:
  name: {{ include "residents-api.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "residents-api.labels" . | nindent 4 }}
type: Opaque
data:
  # Oracle ATP credentials (base64 encoded)
  oracle-username: {{ .Values.secrets.oracleCredentials.username | b64enc | quote }}
  oracle-password: {{ .Values.secrets.oracleCredentials.password | b64enc | quote }}
  
  # Cloudflare R2 credentials (base64 encoded)
  cloudflare-access-key-id: {{ .Values.secrets.cloudflareCredentials.accessKeyId | b64enc | quote }}
  cloudflare-secret-access-key: {{ .Values.secrets.cloudflareCredentials.secretAccessKey | b64enc | quote }}
  cloudflare-account-id: {{ .Values.secrets.cloudflareCredentials.accountId | b64enc | quote }}
  
  # Application secrets (base64 encoded)
  jwt-secret: {{ .Values.secrets.appSecrets.jwtSecret | b64enc | quote }}