apiVersion: v1
kind: Service
metadata:
  name: {{ include "residents-api.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "residents-api.labels" . | nindent 4 }}
  annotations:
    # Oracle Cloud Load Balancer annotations for free tier
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "10"
    service.beta.kubernetes.io/oci-load-balancer-backend-protocol: "HTTP"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "residents-api.selectorLabels" . | nindent 4 }}