// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEZqKHv3SyuzCKxvh3k4D7F97XGIHi80s',
    appId: '1:301880694626:web:7225f3f702fdab15a1fe3b',
    messagingSenderId: '301880694626',
    projectId: 'beresheet-app',
    authDomain: 'beresheet-app.firebaseapp.com',
    storageBucket: 'beresheet-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEZqKHv3SyuzCKxvh3k4D7F97XGIHi80s',
    appId: '1:301880694626:android:7225f3f702fdab15a1fe3b',
    messagingSenderId: '301880694626',
    projectId: 'beresheet-app',
    storageBucket: 'beresheet-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEZqKHv3SyuzCKxvh3k4D7F97XGIHi80s',
    appId: '1:301880694626:ios:your-ios-app-id',
    messagingSenderId: '301880694626',
    projectId: 'beresheet-app',
    storageBucket: 'beresheet-app.firebasestorage.app',
    iosBundleId: 'com.home.beresheet-app',
  );
}